### PR TITLE
quote file paths in racer commands

### PR DESCRIPTION
**Pull request by dten**
The file paths might contain spaces (mostly doesn't for temp but definitely can for the src file)

### CODE REVIEW

**Comment by Draivin** [comment]
Could you remove the escaping slashes to be more consistent with the rest of the codebase?

**Comment by dten** [comment]
I'm new to typescript :) didn't know you don't need them

**Comment by dten** [comment]
i squashed the commits

**Comment by saviorisdead** [comment]
Hi there
Thank you for contribution :)

**Comment by saviorisdead** [comment]
Reverted for now, until racer bug referenced here #45 is fixed.

**Pull request merged**
