### PR TITLE
Change rustfmt exec method

### PR DESCRIPTION
**Pull request by Draivin**
Potential fix for #112  and #99.

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
I'll try it.

**Comment by KalitaAlexey** [comment]
Now it works for me.

**Comment by KalitaAlexey** [comment]
@saviorisdead Do not merge it.

**Comment by saviorisdead** [comment]
So, what's the status of this?

**Comment by KalitaAlexey** [comment]
Check format for code
```rust
pub trait Canvas {
    fn draw_line(&mut self,)
}
```
Code will be
```rust
pub trait Canvas {}
```
rustfmt exited with code 0, but the output has
```
canvas.rs:3:1: 3:2 error: expected `;` or `{`, found `}`
canvas.rs:3 }
```

**Comment by KalitaAlexey** [comment]
I opened the issue: https://github.com/rust-lang-nursery/rustfmt/issues/976

**Comment by KalitaAlexey** [comment]
This PR fixes rustfmt for me, but format on save may corrupt someone code.

**Comment by Draivin** [comment]
@KalitaAlexey added a workaround, could you test again?

**Comment by KalitaAlexey** [comment]
Yes. Wait a minute.

**Comment by KalitaAlexey** [comment]
Yes this works.

**Comment by Draivin** [comment]
@saviorisdead should be fine to merge then. :)

**Comment by saviorisdead** [comment]
All fixed? Awesome. I'l take a look at the code and merge if everything is ok.

**Comment by saviorisdead** [comment]
Ok, looks good for me.

**Pull request merged**
