### PR TITLE
Update hover provider for better appearance

### PR DESCRIPTION
**Pull request by Draivin**
Some comparisons:

- Before:
image
- After:
image

- Before:
image
- After:
image

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
Very good.

**Comment by saviorisdead** [comment]
Looks awesome! Thank you for your contribution.

**Comment by zummenix** [comment]
I'm sorry for asking here.
Are there any settings in vs code that disable this hover or make it appear using keyboard command?
It is very irritating when I move cursor around and see this.

**Comment by Draivin** [comment]
We probably should create an option for enabling it, could you open an issue?

**Comment by zummenix** [comment]
@Draivin, I'm not sure it's correct to add the option in RustyCode rather than in VSCode.

**Pull request merged**
