### PR TITLE
fixes issue #104, racer backtrace support

### PR DESCRIPTION
**Pull request by seanjensengrey**
we now see a full backtrace in the racer error log

### CODE REVIEW

**Comment by Draivin** [comment]
Hello there, the current way you are passing the environment variables will not allow for any of the outer process environment variables to apply to racer.

The correct way to do that is to extend the current `process.env` with the new environment variables you want to set. You could use [`Object.assign`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) to do this.

**Comment by seanjensengrey** [comment]
I see that. Not sure I would want all of those passed to racer though.  This is a great rundown of how to do what you are describing.

https://gist.github.com/leommoore/4484379

**Comment by saviorisdead** [comment]
Actually, I am planning to add setting to set `CARGO_HOME` via settings, so this PR could be useful as an idea.

**Comment by saviorisdead** [comment]
Thank you for the idea, closing this PR as it is not needed anymore.
Still much appreciated anyway 👍

**Comment by seanjensengrey** [comment]
Np, I just wanted to capture the racer backtraces so they would/could get fixed. 

Keep on Rusting!

**Pull request closed without merging**
