### PR TITLE
Better processing of JSON-encoded diagnostic messages.

### PR DESCRIPTION
**Pull request by mitskevich**
Some improvements to a processing of JSON messages (taken from Atom's plugin [linter-rust](https://github.com/AtomLinter/linter-rust)):

* Displaying message notes.

* Following macro expansion to get correct filename and range.

* Showing error code and label from primary span.

### CODE REVIEW

**Comment by W4RH4WK** [comment]
Thank you for all the great pull requests, it is much appreciated. Please be patient, it may take some time until they are merged.

**Comment by mitskevich** [comment]
@W4RH4WK Thanks! No problem, RustyCode is a great extension that I use excessively in my daytime job, so I'm fixing/adding things that I need myself anyway... Please let me know if you find anything that I have missed or broken accidentally :)

**Comment by KalitaAlexey** [comment]
Hi @mitskevich,

Unfortunately, the main maintainer isn't available.

I made a fork of this extension.
I will be glad, if you open the PR in my repository: https://github.com/KalitaAlexey/vscode-rust

Regards,
Alexey

**Comment by mitskevich** [comment]
@KalitaAlexey, sure, I'll rebase and send PRs to your repository in a few days when I'll have some free time. I'm also working on few other RustyCode issues, I'll make PRs for them directly to your fork when those will be ready. Thanks you for keeping the project alive!

**Comment by KalitaAlexey** [comment]
@mitskevich,
Before you start to do something, look at the commits. Maybe I have already commited it.

**Comment by mitskevich** [comment]
Rebased to KalitaAlexey/vscode-rust#3.

**Pull request closed without merging**
