### PR TITLE
Added commands to {build, run} current example

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by saviorisdead** [comment]
Hi and thank you for contribution.
Please run `gulp tslint` and fix linter issues if you can :)

**Comment by KalitaAlexey** [comment]
I have no `gulp`.

**Comment by saviorisdead** [comment]
Then you should do following steps:  
```bash
npm install -g gulp
cd /path/to/your/fork/of/RustyCode/
gulp tslint
```
Then you should see list of style errors which need to be fixed :)

**Comment by Draivin** [comment]
You can also see the error list here:
https://travis-ci.org/saviorisdead/RustyCode/builds/96774554

**Comment by KalitaAlexey** [comment]
I fixed styles

**Pull request merged**
