### PR TITLE
fixed #100. added status bar item that indicating racer status

### LINKED ISSUE #100: Add an option to disable racer crash report
Racer crash report is quite annoying, we may need an option to disable this report and restart it automatically after some interval.

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by seanjensengrey** [comment]
I just gave this a test, I like it. It is hardly noticeable that racer crashes so often.

But I no longer see the racer crash log in the output window. It would be nice to still log the racer failures so they can be fixed?

**Comment by KalitaAlexey** [comment]
@seanjensengrey When you see "Racer: Crashed" you have one second to click on the status item to see output log. I will make it available to click also on "On|Off" to show previous crash error.

**Comment by KalitaAlexey** [comment]
I increased racer restart delay to 3 seconds. You will have enough time to click on racer status item.

**Comment by saviorisdead** [comment]
Thank you.

**Pull request merged**
