### PR TITLE
Added command to open playground.

### PR DESCRIPTION
**Pull request by KalitaAlexey**
Open playground makes the following things:
* Creates temporary directory
* Initializes directory for binary project (`cargo init --bin`)
* Opens new VSCode window in that directory.

Sometimes I want to check some feature in separated project. It helps me a lot.

### CODE REVIEW

**Comment by saviorisdead** [comment]
I am not sure about this. If we talking about quick testing of some features, may be we should consider some integration with `http://play.rust-lang.org/`?
As for this PR I guess I'll wait for some poll reactions from users.

**Comment by KalitaAlexey** [comment]
@saviorisdead VSCode better than play.rust-lang.org
Fetch this PR and try youself. I think you will love that.

**Comment by KalitaAlexey** [comment]
Everyone I am asking for reaction.

**Comment by Draivin** [comment]
I think it could be useful, but we are getting kinda bloated on commands, do we really need `Build Example, Debug` and `Build Example, Release`?

**Comment by KalitaAlexey** [comment]
Not any more. I fixed that long time ago.

**Comment by KalitaAlexey** [comment]
Currently **build** builds correctly for example if chosen example - build example

**Comment by Draivin** [comment]
It seems that was done in this pull request https://github.com/saviorisdead/RustyCode/pull/54/, which was never merged.

Currently **build** executes a cargo command directly, without any path checks.

**Comment by KalitaAlexey** [comment]
You are right.

**Comment by saviorisdead** [comment]
Closing this cause of lack of response from users/contributors.
I am still open to discuss if someone has interest/demand in this feature.
Anyway, @KalitaAlexey thank you for your effort. 👍

**Pull request closed without merging**
