### PR TITLE
Fix breakage of ctrl+hover functionality on racer daemon restart

### PR DESCRIPTION
**Pull request by Soaa-**
Superseded by #85

### CODE REVIEW

**Comment by Draivin** [comment]
I'm not sure if it the pending callbacks should be invoked, perhaps the array should just be cleared? Any opinions?

**Comment by Soaa-** [comment]
The array is already cleared when the daemon is restarted. The issue stems from VS Code waiting for a callback and never getting it.

Basically, VS Code receives a Thenable (Promise) from `definitionProvider`, but when racer panics, the callback never gets called.

**Comment by Draivin** [comment]
I see, thanks. Looks good to me.

**Comment by Soaa-** [comment]
Closed in favor of #85, to free up my master branch

**Pull request closed without merging**
