### PR TITLE
Fixed a bug with check on save not working if formatting failed.

### PR DESCRIPTION
**Pull request by trixnz**
If formatting fails, the file is not modified. As a result, a second onDidSaveTextDocument event is not fired which prevents the checkOnSave functionality from occurring.

A reliable test case for this is to intentionally write code with syntax errors and save it. Formatting will fail and the check will not run, which makes it annoying to troubleshoot why.

### CODE REVIEW

**Comment by CryZe** [comment]
Oh wow, this is the only reason I don't have format on save active. Thank you for fixing that :O

**Comment by trixnz** [comment]
I can't take the credit, I just copied the Go implementation :). However, I shared your pain!

**Comment by saviorisdead** [comment]
Good catch. Ready to merge, as soon as conflicts will be resolved, so rebase please :)

**Comment by trixnz** [comment]
Should be good to go now, although Travis seems to be having some [issues](https://www.traviscistatus.com/incidents/mjyq8dprd2zx).

**Comment by saviorisdead** [comment]
Looks like Travis alive again and all tests have passed, so merging.
Thank you for improving `RustyCode` and `Rust` tooling in general. 👍

**Pull request merged**
