### PR TITLE
Removed warning message about failed cargo

### PR DESCRIPTION
**Pull request by KalitaAlexey**
It is useless. Same warning is shown in output channel

### CODE REVIEW

**Comment by Draivin** [comment]
Have in mind that a command can be run with no output channel, so this could be the only way to tell that an error has happened.

**Comment by Draivin** [comment]
It appears the error code for compilation error is 101, so perhaps you could hide the error message just in that case.

**Comment by KalitaAlexey** [comment]
@Draivin Output channel will be opened if there is no one.

**Comment by Draivin** [comment]
The argument that controls if the cargo command is headless is the `visible` argument to `runCargo`, it is there to allow "headless" cargo commands, with no output pannel. If you run such a command, it would be good to be able to report an unexpected failure, this was the reason the error message is there.

It seems as if the `101` exit codes in cargo relate to execution failures, when cargo delegates the command it is running to a third party, such as the `rustc` compiler, so we could potentially ignore only those errors on the warning message, and any other cargo exit codes, such as `127` for unknown command, could still be shown with the warning message.

If this somehow conflicts with your workflow please tell me how, so we can arrive on some common terms where there is still some error feedback in case a command is run with `visible` set to false.

**Comment by KalitaAlexey** [comment]
@Draivin I agree with you. I fix code to show warning only if code != 101

**Pull request closed without merging**
