### PR TITLE
Fixed cargo process working directory to work with multiple projects

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by Draivin** [comment]
`activeTextEditor` can be undefined, in which case it should revert to the previous behaviour.

**Comment by KalitaAlexey** [comment]
@Draivin Oh. You are right. I will fix it.

**Comment by KalitaAlexey** [comment]
@Draivin No, you are not right. We cannot build without active text editor. Try youself.

**Comment by Draivin** [comment]
I forgot that the extension doesn't register handlers until a rust file has been opened, in which case you are right.
But it still can happen when a previously active text editor has been closed, though I am not sure we wan't to handle such an edge case.

**Comment by KalitaAlexey** [comment]
@Draivin You mean moment after user pressed build and closed editor? I think this is really little moment.

**Comment by Draivin** [comment]
No, I mean when you closed all the open files on the workspace, you can still build but it will throw an error:
`"Cannot read property 'document' of null"`

Also, I tested the changes and it does not seem to work properly, it will use the folder the file is in as the working directory for cargo, and cargo does not automatically traverses upwards until it reaches a toml.

The correct way to implement it would be to traverse the directories upwards from the current active file until we find a directory where there is a toml file, and use that directory as the cwd.

**Comment by KalitaAlexey** [comment]
@Draivin Let me check.

**Comment by Draivin** [comment]
@KalitaAlexey Ignore what I said about cargo not traversing upwards, I was wrong.

**Comment by KalitaAlexey** [comment]
Which error?

**Comment by Draivin** [comment]
Printing code:
image

With file open:
image

After closing file:
image

**Comment by KalitaAlexey** [comment]
This is another issue.

**Comment by Draivin** [comment]
This is exactly what I was talking about in the first post.

**Comment by KalitaAlexey** [comment]
No. You talked about multiple projects in one workspace. I fixed that. This is another case. Please fill another issue for that.

**Comment by Draivin** [comment]
This error is caused by handling multiple projects in one workspace without checking if `activeTextEditor` is `null`. It does not exist currently, it will exist if this pull requested is commited as-is.

**Comment by KalitaAlexey** [comment]
Ok. I got it. I will fix it.

**Comment by icorderi** [comment]
+1, looks good. 
@KalitaAlexey, defaulting to _$workspace_ when there is no window active seems reasonable (`activeTextEditor = null` case). It's the behavior we have right now.

**Pull request merged**
